import 'dart:io';
void main(){
  int num = 19;
  print(num.isEven);
  print(num.isOdd);
  print(num.isFinite);
  print(num.isInfinite);
  print(num.isNaN);
  print(num.isNegative);
  print(num.sign);
  print(num.hashCode);
  print(num.abs());
  print(num.ceil());
  print(num.floor());
  print(num.compareTo(50));
  print(num.remainder(150));
  print(num.round());
  print(num.toDouble());
  print(num.toInt());
  print(num.toString());
  print(num.truncate());
}